/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategistRouteImport } from './routes/strategist'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as ResumesRouteImport } from './routes/resumes'
import { Route as RecruitersRouteImport } from './routes/recruiters'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrepRouteImport } from './routes/prep'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ConversionRouteImport } from './routes/conversion'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksTickRouteImport } from './routes/api/public/hooks/tick'

const StrategistRoute = StrategistRouteImport.update({
  id: '/strategist',
  path: '/strategist',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesRoute = ResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruitersRoute = RecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepRoute = PrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionRoute = ConversionRouteImport.update({
  id: '/conversion',
  path: '/conversion',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickRoute = ApiPublicHooksTickRouteImport.update({
  id: '/api/public/hooks/tick',
  path: '/api/public/hooks/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/companies': typeof CompaniesRoute
  '/conversion': typeof ConversionRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/onboarding': typeof OnboardingRoute
  '/outreach': typeof OutreachRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/resumes': typeof ResumesRoute
  '/sources': typeof SourcesRoute
  '/strategist': typeof StrategistRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/companies': typeof CompaniesRoute
  '/conversion': typeof ConversionRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/onboarding': typeof OnboardingRoute
  '/outreach': typeof OutreachRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/resumes': typeof ResumesRoute
  '/sources': typeof SourcesRoute
  '/strategist': typeof StrategistRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/approvals': typeof ApprovalsRoute
  '/automation': typeof AutomationRoute
  '/companies': typeof CompaniesRoute
  '/conversion': typeof ConversionRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/feed': typeof FeedRoute
  '/feedback': typeof FeedbackRoute
  '/follow-ups': typeof FollowUpsRoute
  '/intake': typeof IntakeRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/observability': typeof ObservabilityRoute
  '/onboarding': typeof OnboardingRoute
  '/outreach': typeof OutreachRoute
  '/packages': typeof PackagesRoute
  '/pipeline': typeof PipelineRoute
  '/prep': typeof PrepRoute
  '/profile': typeof ProfileRoute
  '/recruiters': typeof RecruitersRoute
  '/resumes': typeof ResumesRoute
  '/sources': typeof SourcesRoute
  '/strategist': typeof StrategistRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/companies'
    | '/conversion'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/feed'
    | '/feedback'
    | '/follow-ups'
    | '/intake'
    | '/launch'
    | '/login'
    | '/observability'
    | '/onboarding'
    | '/outreach'
    | '/packages'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/recruiters'
    | '/resumes'
    | '/sources'
    | '/strategist'
    | '/api/public/hooks/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/companies'
    | '/conversion'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/feed'
    | '/feedback'
    | '/follow-ups'
    | '/intake'
    | '/launch'
    | '/login'
    | '/observability'
    | '/onboarding'
    | '/outreach'
    | '/packages'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/recruiters'
    | '/resumes'
    | '/sources'
    | '/strategist'
    | '/api/public/hooks/tick'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/approvals'
    | '/automation'
    | '/companies'
    | '/conversion'
    | '/copilot'
    | '/dashboard'
    | '/demo'
    | '/feed'
    | '/feedback'
    | '/follow-ups'
    | '/intake'
    | '/launch'
    | '/login'
    | '/observability'
    | '/onboarding'
    | '/outreach'
    | '/packages'
    | '/pipeline'
    | '/prep'
    | '/profile'
    | '/recruiters'
    | '/resumes'
    | '/sources'
    | '/strategist'
    | '/api/public/hooks/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutomationRoute: typeof AutomationRoute
  CompaniesRoute: typeof CompaniesRoute
  ConversionRoute: typeof ConversionRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  FeedRoute: typeof FeedRoute
  FeedbackRoute: typeof FeedbackRoute
  FollowUpsRoute: typeof FollowUpsRoute
  IntakeRoute: typeof IntakeRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OnboardingRoute: typeof OnboardingRoute
  OutreachRoute: typeof OutreachRoute
  PackagesRoute: typeof PackagesRoute
  PipelineRoute: typeof PipelineRoute
  PrepRoute: typeof PrepRoute
  ProfileRoute: typeof ProfileRoute
  RecruitersRoute: typeof RecruitersRoute
  ResumesRoute: typeof ResumesRoute
  SourcesRoute: typeof SourcesRoute
  StrategistRoute: typeof StrategistRoute
  ApiPublicHooksTickRoute: typeof ApiPublicHooksTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategist': {
      id: '/strategist'
      path: '/strategist'
      fullPath: '/strategist'
      preLoaderRoute: typeof StrategistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes': {
      id: '/resumes'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiters': {
      id: '/recruiters'
      path: '/recruiters'
      fullPath: '/recruiters'
      preLoaderRoute: typeof RecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep': {
      id: '/prep'
      path: '/prep'
      fullPath: '/prep'
      preLoaderRoute: typeof PrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversion': {
      id: '/conversion'
      path: '/conversion'
      fullPath: '/conversion'
      preLoaderRoute: typeof ConversionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick': {
      id: '/api/public/hooks/tick'
      path: '/api/public/hooks/tick'
      fullPath: '/api/public/hooks/tick'
      preLoaderRoute: typeof ApiPublicHooksTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutomationRoute: AutomationRoute,
  CompaniesRoute: CompaniesRoute,
  ConversionRoute: ConversionRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  FeedRoute: FeedRoute,
  FeedbackRoute: FeedbackRoute,
  FollowUpsRoute: FollowUpsRoute,
  IntakeRoute: IntakeRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  ObservabilityRoute: ObservabilityRoute,
  OnboardingRoute: OnboardingRoute,
  OutreachRoute: OutreachRoute,
  PackagesRoute: PackagesRoute,
  PipelineRoute: PipelineRoute,
  PrepRoute: PrepRoute,
  ProfileRoute: ProfileRoute,
  RecruitersRoute: RecruitersRoute,
  ResumesRoute: ResumesRoute,
  SourcesRoute: SourcesRoute,
  StrategistRoute: StrategistRoute,
  ApiPublicHooksTickRoute: ApiPublicHooksTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
