/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksTickRouteImport } from './routes/api/public/hooks/tick'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickRoute = ApiPublicHooksTickRouteImport.update({
  id: '/api/public/hooks/tick',
  path: '/api/public/hooks/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/resume': typeof ResumeRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/resume': typeof ResumeRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/pipeline': typeof PipelineRoute
  '/resume': typeof ResumeRoute
  '/api/public/hooks/tick': typeof ApiPublicHooksTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/copilot'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/outreach'
    | '/pipeline'
    | '/resume'
    | '/api/public/hooks/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/copilot'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/outreach'
    | '/pipeline'
    | '/resume'
    | '/api/public/hooks/tick'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/copilot'
    | '/dashboard'
    | '/jobs'
    | '/login'
    | '/outreach'
    | '/pipeline'
    | '/resume'
    | '/api/public/hooks/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  OutreachRoute: typeof OutreachRoute
  PipelineRoute: typeof PipelineRoute
  ResumeRoute: typeof ResumeRoute
  ApiPublicHooksTickRoute: typeof ApiPublicHooksTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick': {
      id: '/api/public/hooks/tick'
      path: '/api/public/hooks/tick'
      fullPath: '/api/public/hooks/tick'
      preLoaderRoute: typeof ApiPublicHooksTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  OutreachRoute: OutreachRoute,
  PipelineRoute: PipelineRoute,
  ResumeRoute: ResumeRoute,
  ApiPublicHooksTickRoute: ApiPublicHooksTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
